name: test_bank-system

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 git clang-format cmake build-essential libgtest-dev

      - name: Prepare Style Checker
        run: git clone https://github.com/Sarcasm/run-clang-format
              && cp run-clang-format/run-clang-format.py run-clang-format.py
              && rm -rf run-clang-format

      - name: Style Check
        run: python3 ./run-clang-format.py -r --exclude ./JsonParser/json.h ./

      - name: Build
        run: mkdir build
              && cd build
              && cmake ..
              && make

      - name: Test
        run: ./bin/test_bank_system
